### ISSUE TITLE
Missing 'requirements.txt' error message

### ISSUE THREAD

**Issue by fgiraldi** [zaironjacobs/get-chrome-driver#2] opened 2022-09-28 18:40 UTC
When attempting to create a virtualenv with version 1.3.6 this is the `pip` command output:
```
Collecting get-chrome-driver~=1.3.4
  Using cached get-chrome-driver-1.3.6.tar.gz (10 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\svc-qa-automation\AppData\Local\Temp\1\pip-install-vl33qijj\get-chrome-driver_57dd0bdbc79b4b5885b
a45c44cc55dbe\setup.py", line 10, in <module>
          with open('requirements.txt') as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

Python 3.9.0
Both MacOS and Windows10
pip 22.2.2

**Comment by zaironjacobs** [comment] 2022-09-28 22:36
The issue is now fixed in version 1.3.7.

**Closed by zaironjacobs** 2022-09-28 22:36 UTC
